name: Iris ML Pipeline CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Pull data from DVC (GCS)
        run: dvc pull -v

      - name: Run tests
        run: pytest --junitxml=results.xml --maxfail=1 --disable-warnings -q

      # CML plugin
      - name: Post CML Report
        uses: iterative/setup-cml@v2
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: |
            echo "## Pytest Report" > report.md
            pytest -q >> report.md
            echo "" >> report.md
            echo "### DVC Status" >> report.md
            dvc status >> report.md
            cml comment create report.md
